"""플러그인 디렉토리 테스트용 커스텀 에이전트."""

from agent_chain.agents.base import BaseCoderAgent
from agent_chain.core import Context


class PluginCoderAgent(BaseCoderAgent):
    """플러그인으로 로드되는 코더."""

    def generate_code(self, context: Context) -> str:
        code = (
            f"# PLUGIN GENERATED by {self.name}\n"
            f"# 요청: {context.request}\n"
            f"def plugin_function():\n"
            f"    pass\n"
        )
        target_file = self.config.get("target_file")
        if target_file and context.env is not None:
            try:
                context.env.write_file(target_file, code)
                print(f"[PluginCoder '{self.name}'] {target_file}에 코드 작성 완료")
            except Exception as e:
                print(f"[PluginCoder] 파일 쓰기 실패: {e}")
        else:
            print(f"[PluginCoder '{self.name}'] 코드 생성 완료")
        return code
